var MomentConstants = {
  MOMENTS_RECEIVED: "MOMENTS_RECEIVED",
  MOMENT_RECEIVED: "MOMENT_RECEIVED",
  MOMENT_CREATED: "MOMENT_CREATED",
  MOMENTS_FETCHED: "MOMENTS_FETCHED"
};

module.exports = MomentConstants;